### ISSUE TITLE
Would it be practical/possible to put the GHC AST into this?

### ISSUE THREAD

**Issue by alanz** [pascalh/Astview#1]
I am working on the Haskell Refactorer at https://github.com/alanz/HaRe, and would like to have a way to examine the AST (RenamedSource) and token stream, while working on it.

I made a basic attempt at https://github.com/alanz/HaRe/tree/ghc-api/hareview but got stuck on versions of glade/gtk etc.

Would this be possible without too much effort now that you seem to have come back to this again?

Regards
  Alan

**Comment by pascalh** [comment]
Hi Alan,

the astview project has moved into a slightly different direction than just showing abstract syntax trees during the development. To be honest the aspect of showing syntax trees became less important.

My current aim and the reason for me reactivating the project is to bring back the basic feature of viewing abstract syntax trees of arbitrary data types. I will also investigate the cabal dependencies to ease the installation of astview. Right now it is just a prototype, but I really want to put astview to work. What kind of problems did you face during our installation?

After bringing back the basic features of astview, it should be not problem to view the ghc ast with astview. I will keep you informed about the status of the project. I'm looking forward to write a short tutorial how to add the ghc ast, since this should be interesting for other users as well.

Regards, Pascal

**Comment by alanz** [comment]
Hi Pascal

I had problems when I looked at it a few months ago relating to versions of glade and gtk, which I gather have been resolved in the meantime in the upstream libraries. Your version now builds without problems in my setup.

I look forward to your tutorial, as I am hoping this will help to have a clearer view of how a given source element is represented in the AST.

To fully achieve what I would like to do would probably involve significantly extending AstView to have HaRe-specific functions in it. This could be done either by packaging AstView as a library or using it as a base for a new tool.

But I think a first step would be to just add the GHC AST, and see how it goes.

I have also copied @chrisbrown1982 into this discussion, he may also have some input on it.

Alan

**Comment by pascalh** [comment]
Hi Alan,

finally I brought back the basic astview functionality. In addition to that, the documentation and especially the help-file has been improved. In the help file (data/astview.html) or Help/Help or Ctrl-H in astview you can find some introductory words on how the core of astview works. Hopefully this answers your questions. Of course I am up to answer questions here as well.

Coming back to your question how a node in the tree is represented: right now every constructor in the abstract syntax tree is (for the sake of simplicity) represented by its name, thus we have a Tree String as internal data structure. I'm thinking about changing this a little bit, since one should distinguish between constructors, identificators and source locations in the internal data structure: data Node = Constr String | Id String | SourceLoc SrcLoc

I'd like to see astview extended doing HaRe-specific stuff or being a base for a new tool.

Regards, Pascal

**Comment by alanz** [comment]
Hi

Great. I will have a look when I get a chance.

Alan

**Comment by alanz** [comment]
It looks good. I think it might be worthwhile to extend the item being stored in the tree to include an element of 'Maybe Data.Data', so it can store the original syntax tree element if needed.

This could also be required to implement a new Class, to guarantee some interface elements, such as to and from a SrcLoc. This could also define callback operations for when the element is selected in the GUI.

A similar approach has been implemented in the Blobs library, which I moved to Github as https://github.com/alanz/Blobs. It implements a generic presentation and navigation layer, allowing arbitrary data to be stored at each point.,

Alan

**Comment by mpickering** [comment]
Hi Pascal, thanks for the cool tool.

As Alan suggested over two years ago, it was possible to use it to view the GHC AST.

Here is the result - https://github.com/mpickering/Astview/tree/ghcparse

**Comment by pascalh** [comment]
Hi Matthew,

nice to see astview still being interesting for other developers. Feel tree to ask for new features, since I should have some time to work on astview in the next couple of weeks.

The first minor feature is to offer manual selection of parsers. Thus we could use both haskell-src-exts and the ghc ast representation as known astview languages and the user can choose which one to use.

**Comment by pascalh** [comment]
I merged your implementation of GHC-core into the master branch, since astview now supports manual language selection. The user can manually select the parser for haskellexts or haskellcore. Thank you again for your work @mpickering.
